services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: erp-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLUSTER_ID: "MDZjMjJkMTUxOGJmNGNhOW"
    networks:
      - erp-network

  kafka-init:
    image: confluentinc/cp-kafka:latest
    container_name: erp-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Resetting consumer group offsets...'
      kafka-consumer-groups \
        --bootstrap-server kafka:9092 \
        --group user-service-group \
        --topic UserRegistered \
        --reset-offsets \
        --to-latest \
        --execute
      echo 'Done.'
      "
    networks:
      - erp-network
    restart: "no"  # run once and exit

networks:
  erp-network:
    name: erp-network
    driver: bridge